### ISSUE TITLE
Feature request: non-root user inside the Docker container?

### ISSUE THREAD

**Issue by DilumAluthge** [staticfloat/Sandbox.jl#24]
Currently, when I use the `DockerExecutor`, the user inside the Docker container is `root`. For example:

```
julia> using Sandbox

julia> config = SandboxConfig(
           Dict("/" => Sandbox.alpine_rootfs());
           stdin=Base.stdin,
           stdout=Base.stdout,
           stderr=Base.stderr,
       );

julia> with_executor(DockerExecutor) do exe
           run(exe, config, `/bin/sh`)
       end;
/ # whoami
root
/ # exit

julia>
```

It would be great if I could have a non-root user inside the Docker container.

I would also want the user inside the Docker container to be different from the user outside the Docker container. In other words, I want the user inside the Docker container to be:
1. Not root
2. A different username from the user outside the Docker container
3. A different UID from the user outside the Docker container
4. Not in any of the same user groups as the user outside the Docker container

I think we would need to create a temporary home directory for this user, since some software assumes that the user has a home directory.

**Comment by DilumAluthge** [comment]
This feature request corresponds to ["RULE #2 - Set a user"](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Docker_Security_Cheat_Sheet.md#rule-2---set-a-user) from [this guide](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Docker_Security_Cheat_Sheet.md).

**Comment by maleadt** [comment]
The primary sandbox uses user namespaces, where this is not an issue. See https://docs.docker.com/engine/security/userns-remap/.

**Comment by DilumAluthge** [comment]
Closing this as fixed by https://github.com/JuliaContainerization/Docker.jl/pull/16

**Comment by staticfloat** [comment]
For the record, I don't want to do any user management in this package; things will quickly get too complex.  Our userns runner doesn't support users at all; if you want to do something that requires knowledge of users, I suggest some other package, such as the `Docker.jl` linked by Dilum above.
