### ISSUE TITLE
Install the CodeCov app on this repo?

### ISSUE THREAD

**Issue by DilumAluthge** [staticfloat/Sandbox.jl#34]
CodeCov recommends that you install their app: https://github.com/apps/codecov

**Comment by DilumAluthge** [comment]
<img width="637" alt="Screen Shot 2021-04-26 at 02 10 29" src="https://user-images.githubusercontent.com/5619885/116036376-9435dc00-a634-11eb-91dc-18c3538edef1.png">

**Comment by staticfloat** [comment]
As far as I can tell, it is installed.
![image](https://user-images.githubusercontent.com/130920/116160466-edd6ee80-a6a6-11eb-8028-8e5322481772.png)

**Comment by DilumAluthge** [comment]
You are right. If I look at #36, it used the GitHub App:

<img width="806" alt="Screen Shot 2021-04-26 at 18 49 59" src="https://user-images.githubusercontent.com/5619885/116160544-41a20180-a6c0-11eb-8827-49a497b3fca4.png">

**Comment by DilumAluthge** [comment]
Unclear why it was previously using the non-App commenter. But at least it's working now.
