### ISSUE TITLE
Debian rootfs tree hash mismatch

### ISSUE THREAD

**Issue by maleadt** [staticfloat/Sandbox.jl#66]
```
 Downloading artifact: debian-julia-python3-rootfs
┌ Error: Tree Hash Mismatch!
│   Expected git-tree-sha1:   dbeb5829a137e6a49337590543daa77f77eae3ba
│   Calculated git-tree-sha1: c0f2c53b857189e1c8378bd37c3b620ea4843e07
  Downloaded artifact: debian-julia-python3-rootfs
```

Freshly downloaded, on both 1.6 and 1.7.

**Comment by staticfloat** [comment]
This is due to https://github.com/JuliaLang/Pkg.jl/pull/2881.  The treehash of this artifact is in fact incorrectly recorded, as it was built with an affected version of Julia.

Fixed by 57e775ad0e7342b8965e6fc9f0c70850f3c46102
