### ISSUE TITLE
No executor available

### ISSUE THREAD

**Issue by giordano** [staticfloat/Sandbox.jl#75]
```julia
julia> @time Sandbox.select_executor(true)
[ Info: Parsed kernel version "5.15.16-1-lts"
[ Info: Found 115 loaded modules
┌ Warning: Could not find loaded `overlay` module, try `sudo modprobe overlay` or export SANDBOX_SKIP_OVERLAYFS_CHECK=true to disable this check!
└ @ Sandbox ~/.julia/dev/Sandbox/src/UserNamespaces.jl:119
[ Info: Parsed kernel version "5.15.16-1-lts"
[ Info: Found 115 loaded modules
┌ Warning: Could not find loaded `overlay` module, try `sudo modprobe overlay` or export SANDBOX_SKIP_OVERLAYFS_CHECK=true to disable this check!
└ @ Sandbox ~/.julia/dev/Sandbox/src/UserNamespaces.jl:119
┌ Warning: Unable to run `docker ps`; perhaps you're not in the `docker` group?
└ @ Sandbox ~/.julia/dev/Sandbox/src/Docker.jl:27
ERROR: Could not find any available executors for x86_64-linux-gnu-libgfortran5-cxx11-libstdcxx29-julia_version+1.7.1!
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] select_executor(verbose::Bool)
   @ Sandbox ~/.julia/dev/Sandbox/src/Sandbox.jl:89
 [3] top-level scope
   @ ./timing.jl:220 [inlined]
 [4] top-level scope
   @ ./REPL[5]:0
```
I'm pretty sure it used to work for me at some point.  Tests fail for me for this reason.

**Comment by Keno** [comment]
> ```julia
> ┌ Warning: Could not find loaded `overlay` module, try `sudo modprobe overlay` or export SANDBOX_SKIP_OVERLAYFS_CHECK=true to disable this check!
> ```

Maybe overlay is built into the kernel, not as a module?

**Comment by DilumAluthge** [comment]
@vchuravy I believe you once encountered this?

**Comment by giordano** [comment]
`lsmod | grep overlay` turns out empty

**Comment by giordano** [comment]
```
% SANDBOX_SKIP_OVERLAYFS_CHECK=true julia -q
julia> using Sandbox

julia> Sandbox.select_executor(true)
[ Info: Parsed kernel version "5.15.16-1-lts"
[ Info: Testing Unprivileged User Namespaces Executor (read-only, read-write)
UnprivilegedUserNamespacesExecutor

julia> 
% julia -q
julia> using Sandbox

julia> Sandbox.select_executor(true)
[ Info: Parsed kernel version "5.15.16-1-lts"
[ Info: Found 116 loaded modules
[ Info: Found loaded `overlay` module
[ Info: Testing Unprivileged User Namespaces Executor (read-only, read-write)
UnprivilegedUserNamespacesExecutor
```
Note that when running without `SANDBOX_SKIP_OVERLAYFS_CHECK=true` there are now 116 loaded modules, and now `overlay` is there.

**Comment by giordano** [comment]
To be clear, is the `overlay` module _**required**_ for the userns runners?  I'm asking because in BinaryBuilder it is not and I use the priviliged userns runner all the time without problems (also the unpriviliged one would work), so I'm surprised here the test fails because of https://github.com/staticfloat/Sandbox.jl/blob/ed87f079edb1cef60c32ad5fbfbcd38c70a1314a/src/UserNamespaces.jl#L70 Reading #61 it appears the `overlay` is indeed needed in some cases?  I have the same setup as Valentin, unsurprisingly as we both use Arch Linux.

**Comment by giordano** [comment]
Ok, I opened #85 to make the warning more explicit about the fact `overlay` is always needed.
